server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**
          filters:
            - RewritePath=/customer/(?<path>.*), /$\{path}
            - RequestRateLimiter=replenishRate=5,burstCapacity=10
            - AddResponseHeader=X-Cached, "Simulated"

        - id: billing-service
          uri: lb://BILLING-SERVICE
          predicates:
            - Path=/billing/**
          filters:
            - RewritePath=/billing/(?<path>.*), /$\{path}
            - RequestRateLimiter=replenishRate=5,burstCapacity=10
            - AddResponseHeader=X-Cached, "Simulated"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
