spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: yourpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
